spring:
  application:
    name: Symon
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${DB_PASSWORD}
    username: ${DB_USERNAME}
    url: ${DB_URL}
  config:
    import: file:.env[.properties]
  security:
    jwt:
      secret: ${JWT_SECRET}
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLI_ID}
            client-secret: ${GOOGLE_CLI_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URI}
            scope: openid,email,profile
aws:
  access: ${AWS_ACCESS}
  secret: ${AWS_SECRET}